server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8000

spring:
  datasource:
    password: 4e50b477c48ca096c01fa25be5d81c52019b4443d3e3fdcf3c4416b1c366522f
    url: jdbc:postgresql://ec2-3-231-253-230.compute-1.amazonaws.com/d4kgq9e84h4i5
    username: dislnwsankhmds
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true